### ISSUE TITLE
[Minor issues]4chan's new captcha & Dark mode

### ISSUE THREAD

**Issue by WithOpenEyes** [saxamaphone69/ss16#18]
(My blocker-of-choice is uBlock Origin)
(Browser is Firefox ver 89.0.2)
### Blocker
New captcha won't load unless 
**[Blocker filter]**
`*//s.4cdn.org/js/core.min.*.js `
Is commented out; disabled in my filters
![image](https://user-images.githubusercontent.com/54213996/124782758-61fe0000-df3c-11eb-8d41-ea36a240139e.png)

### Dark mode

Dark mode's default colors obscure the new captcha entry text box.
this is the default light theme
![image](https://user-images.githubusercontent.com/54213996/124777435-1cd7cf00-df38-11eb-8512-2f6d5d63b6b8.png)
this is how it looks in dark mode
![image](https://user-images.githubusercontent.com/54213996/124777564-35e08000-df38-11eb-807e-dd96e8f4e90c.png)
The problem is the text in the text box becomes unreadable with the default settings, you can still use it and post fine, but you won't be able to see what you type in it.
if you change the `ss21TextPrimary color`
![image](https://user-images.githubusercontent.com/54213996/124778336-d040c380-df38-11eb-9d3d-31c058020835.png)
you'll be able to see what you're typing
![image](https://user-images.githubusercontent.com/54213996/124778425-e2bafd00-df38-11eb-9083-069f2abe160d.png)
but this comes at the expense of changing a lot of the colors you'll see in a thread. 
![image](https://user-images.githubusercontent.com/54213996/124781927-b6ed4680-df3b-11eb-9f1c-0cc8c7dcba78.png)
My guess is the box isn't inverting properly not sure, only seems to be an issue if you use default dark mode.

**Comment by saxamaphone69** [comment]
I was waiting for the new captcha to settle and 4chan X to do it's thing, but give https://github.com/saxamaphone69/ss21/commit/7e17fd02f0a15a14683ebba5496ddc06ea88ad8f a go and tell me if it's better.

Also thank you so much for using the userstyle, if you have any other concerns/wishes please let me know.

**Comment by WithOpenEyes** [comment]
Hey, of course what you said about waiting for 4chan X to settle makes perfect sense, it only occurred to me that might be your intention after the fact. 
My apologies.

**`7e17fd0`**
Works perfectly 
![image](https://user-images.githubusercontent.com/54213996/124975740-3c4d2580-e026-11eb-87ae-388c8852a4bd.png)
I think the inversion of the captcha itself is a cool touch. 
Text entered doesn't automatically become capital like it did previously, however captcha does not seem to be case-sensitive and accepts lower case entries just fine. 

Thank you for the speedy response and fix despite it being a non-critical issue.
Also, thank you for making the userstyle in the first place, I think it's great.

**Comment by saxamaphone69** [comment]
Any other little (or big) things, please feel free to open a new issue and let me know.
