### ISSUE TITLE
Post Navigation Rail Update; Catalog display

### ISSUE THREAD

**Issue by WithOpenEyes** [saxamaphone69/ss16#23]
Post the navigation rail update, the catalog threads are displayed differently, I'm not sure if it's user error on my part, but I did look through the settings and I do not think I've overlooked a setting for how threads are displayed.
![image](https://user-images.githubusercontent.com/54213996/204143004-86f13e31-943a-4e16-a526-381b912f99ce.png)
The above picture is the latest user style version 2.2.4; The below the previous before navigation rail Version 2.2.1
![image](https://user-images.githubusercontent.com/54213996/204142478-49cf4f9b-74ae-4b13-88f9-eac574061453.png)
In my opinion, 2.2.4 looks less appealing on certain boards with long-running threads or text intensive opening posts and was wondering if the option to return to the previous more uniform style was available or if it's a toggle I did overlook.

Not a big issue, as one can give up the sleekness of the new navigation rail and simply revert to 2.2.1, I was just curious if it's a design decision or if I've overlooked something obvious. 
Thanks for creating and sharing the style.

**Comment by saxamaphone69** [comment]
Thanks for taking the time to open another issue, I appreciate it.

I'm trying to (in combination with sidedish) make it so the catalogue appears in a masonry layout:
![image](https://user-images.githubusercontent.com/877480/204452466-32d93e8d-eff8-454a-bbc8-25ea2ab56296.png)

Recently I even have it so thumbnails in the catalogue prefetch their full size OP and replace it automatically.

But I do agree, there is still a place for the 2.2.1 layout (that is, defined rows and long threads are cut off - heck I'm not even sure if I supported the full card to appear on hover - I should if I don't).

Come the holidays I'll definitely put this behind a toggle/option to switch between masonry and defined rows (which is the default 4chan X option).

You might want to stick with 2.2.1 if that's the case - I don't currently have any fallbacks implemented if certain options are/aren't enabled.

As always, if there's anything else that doesn't work with your workflow please let me know because AFAIK I'm the only one using the style so if it works for me, I won't know if it breaks for someone else. Same with any nice to have features.

**Comment by saxamaphone69** [comment]
Let me know how `2.2.5` goes.

**Comment by WithOpenEyes** [comment]
Hi, thank you for updating and including the catalogue toggle in 2.2.5

**Default-Esque** looks great with how threads are displayed into single row/column for smaller/ Double row/column for larger with the expand on feature. A few issues I've noticed are.
<div id="image-table">
    <table>
	    <tr>
    	    <td style="padding:10px">
        	    <img src="https://user-images.githubusercontent.com/54213996/207172392-72a0c161-dc91-4ce7-88d1-382bf1e0ae74.png" width="400"/>
      	    </td>
            <td style="padding:10px">
            	<img src="https://user-images.githubusercontent.com/54213996/207172766-a3add09d-d04f-40a8-b2d8-6d5a571272d3.png" width="400"/>
            </td>
                 <td style="padding:10px">
            	<img src="https://user-images.githubusercontent.com/54213996/207175813-26251cda-48ed-4503-9015-e5fc0f53c2c0.png" width="400"/>
            </td>
        </tr>
    </table>
</div>
- Sometimes Smaller Single Row/Column threads will occupy the bottom half of Larger Double Row/Column threads. 
Minor issue as the thread will expand the card on mouseover and the thread will become fully visible while mouseovered.
In extreme cases, 4 smaller threads can cover 1 larger thread, like in the picture on the right above.

![image](https://user-images.githubusercontent.com/54213996/207174284-ccaf18b2-3717-4418-8f29-ffc06d31daa4.png)
- There are smalls gaps that aren't an issue but tend to be really noticeable towards the bottom of a page
<div id="image-table">
    <table>
	    <tr>
    	    <td style="padding:10px">
        	    <img src="https://user-images.githubusercontent.com/54213996/207175005-528fe410-4e31-4a1c-925a-39bf58a3a278.png" width="400"/>
      	    </td>
            <td style="padding:10px">
            	<img src="https://user-images.githubusercontent.com/54213996/207175287-c2522874-246a-4e48-bd1f-ad98cc3aa695.png" width="400"/>
            </td>
        </tr>
    </table>
</div>

 - The only major issue; Threads can sometimes be stacked on top of each other, with only a small overlap at the bottom of a thread as an indicator.

On boards where one size of thread becomes much more consistent like /vg/, after hiding all the smaller threads, larger threads were displayed without any issues. 

While it offers two distinct appeals, those being :a row by row uniform approach to organisation which might be easier for some people to process information & For boards that feature long opening posts like /vg/,/t/.
On text intensive boards like /adv/ masonry looks fine whereas usecases like /vg/ and /t/ are somewhat rarer on the website as whole.
It might be better to simply force one size, either a smaller or larger card for default-esque depending on how trying creating a uniform style is.   

**Masonry** 
I like masonry more in this version, it displays more consistently, and I think it looks very nice.
For the average board, which is made up of both large and small thread, it displays them perfectly.
Occasionally one column will stack threads towards the end, but it's hardly an issue as the threads are still plainly readable. 
Occasionally it will display weird padding between threads, but a refresh of the page will usually fix that. 
Ironically, it comes with the (buggy) name but is less buggy than default-esque.

In terms of issues besides the catalogue. I can't really think of any.
When you added the new icons to favourite a thread, I think my icon wouldn't display properly.
I was going to make that an issue, but I saw you had already created one, that and I swapped to the star which displayed fine. 
I'm using Firefox dev, which may or may not be relevant. with Violentmonkey and stylus. 
Thanks again for the update and happy holidays.

**Comment by saxamaphone69** [comment]
Thank you for all this detail.

Also just curious, do you have the filters for "long" threads or threads with lots of new lines?

I didn't actually test replies on hover in masonry mode, will have to do that too.

I think I know the issue - Firefox supports CSS Grid `masonry`, so maybe it's applying as intended, rather than being a workaround as in Chrome. I'll have to test in Firefox.

Another issue I think exists is that switching modes doesn't sometimes make/apply the change correctly. For example, going from paged view to catalog view, then switching from masonry to default-esque.

That also makes me think that hiding a thread from the catalog doesn't "redraw" the grid, which would also cause issues.

I should make "watch thread" an option to appear in catalog mode, cause at the moment it only appears in within the menu.

le edit: the `transform` I apply when hovering ruins the menu positioning, going to have to use negative margins (gross)

I'll keep looking into it. Thank you again so much.

**Comment by WithOpenEyes** [comment]
> Also just curious, do you have the filters for "long" threads or threads with lots of new lines?

Just as you suspected I did have comment filters ; I was using the ones suggested in the readme.md
The culprits seem to be:
>/^\W*(\w+\b\W*){91,149}$/;op:only;top:no;highlight:thread--extra-long
>/^\W*(\w+\b\W*){150,}$/;op:only;top:no;highlight:thread--silly-long
>/(?:[^\n]*(\n+)){5,}/;op:only;top:no;highlight:thread--new-lines

 Upon commenting them out, **Default-esque** displayed all thread cards as small or large depending on the selection at the top of the Catalog and had no issues. 
I apologise, it's really something I should have remembered to check. 
 Catalog  small        |    Catalog   Large 
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/54213996/207311725-0022c514-014d-4138-a06f-c91ca045a37d.png) |  ![](https://user-images.githubusercontent.com/54213996/207340676-8df38428-926e-48c2-a289-058c39a8049c.png)

The first comment filter
 >/^\W*(\w+\b\W*){50,90}$/;op:only;top:no;highlight:thread--long

Seems to now be superfluous as well, but having it neither breaks **default-esque** nor does it cause any changes i've been able to notice.
**Masonry** seems to operate properly regardless of those comment filters being active or not. 

As far as I can tell, Catalog hover expand replies aren't functional, in **default** or **masonry**.
 Thread stacking at bottom of board           |   screenshot 2  
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/54213996/207324038-97f56c0d-2065-4d15-929d-c4d7d899047b.png) |  ![](https://user-images.githubusercontent.com/54213996/207324299-aa04e8ba-bcb3-466d-822b-39d4ca6766b8.png)
Top half | Bottom Half

**Masonry** works very well and in worse case I'd just switch to a chromium based browser if **Firefox** ever was the cause of a large problem. But having done some brief testing in **Edge** I think they are operating the same.

>Another issue I think exists is that switching modes doesn't sometimes make/apply the change correctly. For example, going from paged view to catalog view, then switching from masonry to default-esque.

I can't speak about paged to Catalog, I'm more likely to swap via the header. The few times I tried it, it worked anticipated. 

 Masonry -> Default           |   Default -> Masonry
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/54213996/207351029-a385f7cb-08de-4c43-b485-b6307d5b2241.png) |  ![](https://user-images.githubusercontent.com/54213996/207351703-7da23245-9bba-4a40-8db7-4f3173221ed0.png)


Yeah, as you've said, it can result in some interesting layouts, but a Catalog refresh seems to rectify any issue one has after these swaps.

A separate issue I've found is on **paged** when enable board title and banner option is disabled, the Catalog bar becomes inaccessible due to the page scrolling down past it, you can collasp a thread, and it becomes accessible again ; the bar won’t scroll down past it. 
It operates normally with the board title and banner option enabled, not scrolling past it.
![image](https://user-images.githubusercontent.com/54213996/207347045-71063317-0616-471b-b813-a1bde80add6f.png)
![image](https://user-images.githubusercontent.com/54213996/207348816-bc228164-c7f8-4df2-a5fd-076857653877.png)

Thank you very much for adding the default-esque format to the Catalog. It's very much appreciated.
